export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const PURCAHSE_BURGER = 'PURCAHSE_BURGER';
export const ORDER_BURGER = 'ORDER_BURGER'
export const ORDER_BURGER_FAIL = 'ORDER_BURGER'
export const ORDER_BURGER_START = 'ORDER_BURGER_START'

export const ORDER_INIT = 'ORDER_INIT'
export const FETCH_ORDER = 'FETCH_ORDER'
export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED'

export const DEL_ORDER = 'DEL_ORDER'